# Generated by Django 3.2.8 on 2022-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_id', models.TextField(max_length=200, verbose_name='Cause ID')),
                ('label', models.TextField(max_length=200, verbose_name='Cause Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cause Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cause Updated')),
                ('tickets', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ticket Count')),
            ],
        ),
    ]
