# Generated by Django 3.2.8 on 2021-10-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='last_ticket',
        ),
    ]
