# Generated by Django 3.2.8 on 2021-10-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.TextField(max_length=200, verbose_name='Ticket ID')),
                ('label', models.TextField(max_length=200, verbose_name='Ticket Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ticket Updated')),
                ('opened', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Opened')),
                ('closed', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Closed')),
                ('affirmer', models.TextField(max_length=200, verbose_name='Ticket for Affirmer')),
                ('notes', models.TextField(verbose_name='Ticket Notes')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='type.type', verbose_name='Ticket Type')),
            ],
        ),
    ]
