# Generated by Django 3.2.8 on 2021-10-30 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='contributors',
            field=models.TextField(null=True, verbose_name='Ticket Contributors'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fix',
            field=models.TextField(null=True, verbose_name='Ticket Fix'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference',
            field=models.TextField(null=True, verbose_name='Ticket Reference'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ticket Initial Response'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(null=True, verbose_name='Ticket Notes'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='opened',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ticket Initially Opened'),
        ),
    ]
