# Generated by Django 3.2.8 on 2021-10-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20211030_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='label',
        ),
    ]
