# Generated by Django 3.2.8 on 2021-10-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20211030_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Ticket Archived'),
        ),
    ]
