# Generated by Django 3.2.8 on 2021-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMeanTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_response', models.DurationField(verbose_name='Mean Time to Response')),
                ('ticket_count', models.IntegerField(verbose_name='Ticket Count')),
            ],
            options={
                'db_table': 'ticket_meantimes',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='delta',
            field=models.DurationField(blank=True, null=True, verbose_name='Business Lapse Delta'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lapse',
            field=models.DurationField(blank=True, null=True, verbose_name='Business Lapse'),
        ),
    ]
