# Generated by Django 3.2.8 on 2021-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMeanTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_response', models.DurationField(verbose_name='Mean Time to Response')),
                ('ticket_count', models.IntegerField(verbose_name='Ticket Count')),
            ],
            options={
                'db_table': 'ticket_meantimes',
                'managed': False,
            },
        ),
    ]
