# Generated by Django 3.2.8 on 2021-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20211104_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketWeeklyResponseTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.DurationField(verbose_name='Mode Response Time')),
                ('week', models.IntegerField(verbose_name='Calendar Week')),
                ('year', models.IntegerField(verbose_name='Calendar Year')),
            ],
            options={
                'db_table': 'ticket_mode_response_per_week_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='regression',
            field=models.BooleanField(default=False, verbose_name='Regression related'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='regression_url',
            field=models.TextField(null=True, verbose_name='Regression / Build URL'),
        ),
    ]
