# Generated by Django 3.2.8 on 2021-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20211108_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='exported',
            field=models.BooleanField(default=False, verbose_name='Record Exported'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='difficulty',
            field=models.CharField(choices=[('1', '1  - Simplest'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - Bloody hard.')], default='2', max_length=2, verbose_name='Ticket Debug Difficulty'),
        ),
    ]
