# Generated by Django 3.2.8 on 2021-12-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20211208_1409'),
        ('ticket', '0014_auto_20211115_0025'),
    ]

    operations = [
    ]
