# Generated by Django 3.2.8 on 2022-01-17 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20211212_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 16, 25, 47, 626389), verbose_name='Ticket Closed/Resolved'),
            preserve_default=False,
        ),
    ]
