# Generated by Django 3.2.8 on 2022-01-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cause', '0001_initial'),
        ('ticket', '0017_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Cause.cause', verbose_name='Ticket Cause'),
        ),
    ]
