# Generated by Django 3.2.8 on 2022-01-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_ticket_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(null=True, verbose_name='Ticket Closed/Resolved'),
        ),
    ]
